name: qlearning-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.21.6
  - scipy>=1.5.0
  - scikit-learn=1.0.2
  - matplotlib=3.5.1
  - h5py=3.6.0
  - pytorch=1.12.1
  - torchvision=0.13.1
  - torchaudio=0.12.1
  - pip
  - pip:
    - pyro-ppl==1.8.1
    - tensorboard>=2.8.0
    - tqdm==4.64.0

